// Catalog: edit this file to add/update products
// Each product maps to either a subscription, digital key/file, or a service

export const categories = [
  { id: 'subs', name: 'Подписки' },
  { id: 'digital', name: 'Цифровые ключи' },
  { id: 'services', name: 'Услуги' }
];

export const products = [
  {
    id: 'steam-topup',
    title: 'Steam пополнение',
    short: 'Пополнение кошелька, подарочные карты, смена региона.',
    description: 'Легко пополняйте свой аккаунт Steam, покупайте подарочные карты Steam и меняйте регион учетной записи. У нас вы найдете лучшие предложения и гарантию безопасности сделок. Быстрое пополнение и доступ к широкому ассортименту игр и контента. Начните экономить и наслаждайтесь удобством покупок с нами!',
    features: ['Пополнение счёта Steam', 'Карты пополнения Steam'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=997&w=384&h=480&dc=794424031',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 299,
    currency: 'RUB',
    popularity: 100,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'psn-topup',
    title: 'PlayStation Store',
    short: 'Карты пополнения PSN и подписки — быстро и безопасно.',
    description: 'Приобретайте карты пополнения PlayStation Network у нас и мгновенно пополняйте свой аккаунт. Наслаждайтесь доступом к эксклюзивным играм, дополнениям и контенту. Гарантированная безопасность транзакций и отличные цены. Повышайте уровень своего игрового опыта с картами оплаты PSN. Купите карты пополнения PlayStation Network прямо сейчас!',
    features: ['Карты пополнения PSN', 'Активация подписки PSN'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=131&w=384&h=480&dc=794423341',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 499,
    currency: 'RUB',
    popularity: 98,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'xbox-topup',
    title: 'Xbox / Microsoft Store',
    short: 'Карты оплаты Xbox Game Pass и подарочные карты Xbox.',
    description: 'Приобретайте карты оплаты Xbox Game Pass и подарочные карты Xbox для мгновенного пополнения аккаунта и активации подписки. Наслаждайтесь удобными и безопасными транзакциями по конкурентным ценам. Откройте доступ к обширной библиотеке игр и эксклюзивным предложениям уже сегодня. Купите карты оплаты Xbox на площадке Plati.Market и с легкостью активируйте подписку!',
    features: ['Активация подписки Xbox', 'Карты пополнения Xbox'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=192&w=384&h=480&dc=794424005',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 449,
    currency: 'RUB',
    popularity: 96,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'chatgpt-access',
    title: 'ChatGPT',
    short: 'Пополнение счёта, продление подписок и аккаунты с гарантией.',
    description: 'Пополнение счета, продление подписок и продажа аккаунтов ChatGPT по доступным ценам. Быстрая и безопасная покупка аккаунтов с гарантией обновлений. Легкий способ продлить использование искусственного интеллекта ChatGPT с максимальной выгодой.',
    features: ['Пополнение счёта ChatGPT', 'Продление подписки', 'Аккаунты с гарантией'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1267&w=384&h=480&dc=794423195',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 1290,
    currency: 'RUB',
    popularity: 94,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'appstore-itunes',
    title: 'App Store & iTunes',
    short: 'Подарочные карты для пополнения Apple ID.',
    description: 'Приобретайте подарочные карты App Store & iTunes для пополнения баланса Apple ID. Легко и быстро покупайте приложения, игры, музыку и фильмы. Мгновенная доставка кодов на ваш email, безопасные и удобные покупки!',
    features: ['Коды пополнения Apple ID', 'Мгновенная доставка', 'Безопасные покупки'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=90&w=384&h=480&dc=808239313',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 500,
    currency: 'RUB',
    popularity: 92,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'nintendo-eshop',
    title: 'Nintendo eShop',
    short: 'Карты оплаты Nintendo eShop для Switch, 3DS и Wii U.',
    description: 'Приобретайте карты оплаты Nintendo eShop для Nintendo Switch, 3DS и Wii U. Быстрая доставка цифровых кодов, удобные номиналы и безопасные покупки. Пополняйте баланс и наслаждайтесь новыми играми и контентом уже сегодня!',
    features: ['Коды eShop', 'Мгновенная доставка', 'Безопасные покупки'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1056&w=384&h=480&dc=799932324',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 500,
    currency: 'RUB',
    popularity: 90,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'cursor-ai',
    title: 'Cursor',
    short: 'Подписки и аккаунты Cursor AI для генерации кода.',
    description: 'Cursor AI – передовой инструмент на базе искусственного интеллекта для генерации кода и оптимизации работы программистов. У нас вы найдете подписку и аккаунты Cursor AI по доступным ценам, чтобы использовать возможности платформы без ограничений. Совершайте быструю покупку через Plati.Market и получайте удобный доступ к интеллектуальному помощнику уже сегодня!',
    features: ['Подписка Cursor AI', 'Аккаунты Cursor AI'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1580&w=384&h=480&dc=800640836',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 990,
    currency: 'RUB',
    popularity: 88,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'ea-sports-fc-26',
    title: 'EA Sports FC 26',
    short: 'Новый футбольный сезон: улучшенная графика, ИИ и составы.',
    description: 'EA Sports FC 26 — это продолжение популярной футбольной серии от EA, предлагающее улучшенную графику, реалистичную физику и обновленные составы команд. Новая система управления и усовершенствованный ИИ делают матчи еще более захватывающими. Участвуй в карьерном режиме, онлайн-турнирах и сезонных событиях. Поддержка кроссплатформенной игры, лицензированные лиги и клубы. Покажи свои навыки на виртуальном поле!',
    features: ['Спортивный симулятор', 'Кроссплатформенная игра', 'Лицензированные лиги'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1643&w=384&h=480&dc=810901536',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 2590,
    currency: 'RUB',
    popularity: 86,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'battlefield-6',
    title: 'Battlefield 6',
    short: 'Масштабный шутер нового поколения с разрушением окружения.',
    description: 'Battlefield 6 — это масштабный шутер нового поколения с разрушением окружения, современной техникой и динамичными боями на огромных картах. Игра предлагает сражения до 128 игроков, обширный арсенал, кастомизацию снаряжения и поддержку отрядного взаимодействия. Режимы PvP, эпичные баталии и реалистичная графика делают Battlefield 6 одним из самых ожидаемых боевиков. Получите цифровой ключ и начинайте бой уже сегодня. Подходит для Steam и других популярных платформ. Продается на Plati.Market.',
    features: ['Шутер от первого лица (FPS)', 'Разрушение окружения', 'До 128 игроков'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1651&w=384&h=480&dc=808315297',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 1990,
    currency: 'RUB',
    popularity: 85,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'sub-private-wall',
    title: 'Подписка: Закрытый контент',
    short: 'Доступ к приватной стене и эксклюзивным заметкам.',
    description: `Ежемесячная подписка. После оплаты получите действующий код доступа по email.
    Преимущества:
    — ранний доступ к черновикам и идеям
    — закулисье разработки продукта
    — возможность предлагать темы и вопросы`,
    features: ['Код доступа на email', 'Ежемесячное продление', 'Поддержка проекта'],
    cover: 'https://images.unsplash.com/photo-1496302662116-35cc4f36df92?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'subs',
    type: 'subscription',
    price: 99,
    currency: 'RUB',
    period: '/мес',
    popularity: 10,
    addedAt: Date.parse('2025-09-01'),
    recommended: true,
    payment: {
      provider: 'payment-link',
      checkoutUrl: '#REPLACE_STRIPE_OR_YOOKASSA_LINK'
    }
  },
  {
    id: 'newsletter-pro',
    title: 'Подписка: Рассылка PRO',
    short: 'Еженедельные письма: Swift, продукт, дизайн, инсайты.',
    description: 'Подписка на письмо раз в неделю. После оплаты — письмо с подтверждением и ссылкой на архив.',
    features: ['1 письмо в неделю', 'Архив выпусков', 'Отписка в 1 клик'],
    cover: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'subs',
    type: 'subscription',
    price: 249,
    currency: 'RUB',
    period: '/мес',
    popularity: 8,
    addedAt: Date.parse('2025-09-10'),
    recommended: true,
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'ios-app-premium-key',
    title: 'Цифровой ключ: iOS App Premium',
    short: 'Лицензионный ключ для разблокировки функций в приложении.',
    description: 'После оплаты ключ мгновенно придёт на email. Количество активаций: 1 устройство.',
    features: ['Мгновенная доставка ключа', '1 устройство', 'Поддержка email'],
    cover: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 690,
    currency: 'RUB',
    popularity: 9,
    addedAt: Date.parse('2025-08-20'),
    recommended: true,
    preorder: true,
    payment: { provider: 'plati-market', checkoutUrl: '#REPLACE_PLATI_GOOD_URL' }
  },
  {
    id: 'consult-60',
    title: 'Консультация 60 минут',
    short: 'Swift / продукт / UX. Zoom/Telegram созвон, конкретные шаги.',
    description: 'Вы выбираете время, мы созваниваемся, я даю план действий и материалы. После оплаты — письмо с ссылкой на запись слота.',
    features: ['Запись созвона', 'Краткий план на email', 'Материалы и ссылки'],
    cover: 'https://images.unsplash.com/photo-1516383740770-faec02c67a5d?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'services',
    type: 'service',
    price: 2900,
    currency: 'RUB',
    popularity: 7,
    addedAt: Date.parse('2025-09-12'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'setup-integration',
    title: 'Услуга: Подключение интеграции',
    short: 'Настрою оплату + автодоставку ключей для вашего проекта.',
    description: 'Полный цикл: выбор провайдера, настройка Checkout, автоматическая рассылка ключей/писем. Срок: 3–5 дней.',
    features: ['Выбор провайдера', 'Автодоставка', 'Документация и поддержка'],
    cover: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'services',
    type: 'service',
    price: 11900,
    currency: 'RUB',
    popularity: 6,
    addedAt: Date.parse('2025-09-08'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  }
  ,
  {
    id: 'sub-pro-club',
    title: 'Подписка: Клуб PRO',
    short: 'Закрытый чат, ранний доступ к материалам и митапы.',
    description: 'Месячная подписка с доступом в приватный Telegram‑чат, голосования, закулисье и закрытые материалы.',
    features: ['Приватный чат', 'Ранний доступ', 'Митапы'],
    cover: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'subs',
    type: 'subscription',
    price: 490,
    currency: 'RUB',
    period: '/мес',
    popularity: 7,
    addedAt: Date.parse('2025-09-11'),
    recommended: true,
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'figma-pro-key',
    title: 'Ключ: Figma Pro 3 мес',
    short: 'Расширенные функции дизайна и командной работы.',
    description: 'Ключ на 3 месяца Figma Pro. Доставка мгновенно на email после оплаты.',
    features: ['3 месяца', 'Мгновенная доставка', 'Поддержка email'],
    cover: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 990,
    currency: 'RUB',
    popularity: 8,
    addedAt: Date.parse('2025-09-05'),
    preorder: true,
    payment: { provider: 'plati-market', checkoutUrl: '#REPLACE_PLATI_GOOD_URL' }
  },
  {
    id: 'vpn-1y',
    title: 'VPN — 1 год',
    short: 'Надёжный доступ без ограничений. Лицензия на 12 месяцев.',
    description: 'Официальный ключ на 12 месяцев. Поддержка устройств iOS/macOS/Windows/Android.',
    features: ['12 месяцев', 'Несколько устройств', 'Поддержка 24/7'],
    cover: 'https://images.unsplash.com/photo-1559066653-e8d23213bd92?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 1490,
    currency: 'RUB',
    popularity: 9,
    addedAt: Date.parse('2025-09-06'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'openai-keys-pack',
    title: 'Пакет ключей OpenAI API',
    short: 'Пополнение на баланс для экспериментов и прототипов.',
    description: 'Набор предоплаченных ключей для быстрых тестов и прототипирования. Отправка мгновенно.',
    features: ['Предоплата', 'Сразу на почту', 'Подходит для прототипов'],
    cover: 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 1990,
    currency: 'RUB',
    popularity: 6,
    addedAt: Date.parse('2025-09-07'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'audit-ios-app',
    title: 'Аудит iOS‑приложения',
    short: 'Технический и UX‑аудит с планом улучшений.',
    description: 'Анализ архитектуры, производительности и UX. Вы получите pdf‑отчёт и список задач.',
    features: ['PDF отчёт', 'Список задач', 'Созвон 30 минут'],
    cover: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'services',
    type: 'service',
    price: 5900,
    currency: 'RUB',
    popularity: 5,
    addedAt: Date.parse('2025-09-04'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'ux-review-landing',
    title: 'UX‑ревью лендинга',
    short: 'Проверю структуру, месседжи и конверсию.',
    description: 'Подробный разбор мультилейаута + рекомендации по текстам и визуальной иерархии.',
    features: ['Скринкаст', 'Чек‑лист', 'Текстовые правки'],
    cover: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'services',
    type: 'service',
    price: 3900,
    currency: 'RUB',
    popularity: 7,
    addedAt: Date.parse('2025-09-09'),
    recommended: true,
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'newsletter-lite',
    title: 'Подписка: Лёгкая рассылка',
    short: 'Короткие заметки раз в неделю — технологии и продукт.',
    description: 'Лёгкая версия рассылки без архива. Только самое важное за неделю.',
    features: ['1 письмо/неделя', 'Отписка в 1 клик'],
    cover: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'subs',
    type: 'subscription',
    price: 149,
    currency: 'RUB',
    period: '/мес',
    popularity: 5,
    addedAt: Date.parse('2025-09-03'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'spotify-family-slot',
    title: 'Spotify Family — слот',
    short: 'Слот в семейном плане на 1 месяц.',
    description: 'Пришлём пригласительную ссылку после оплаты. Работает в большинстве регионов.',
    features: ['1 месяц', 'Приглашение в семью'],
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 259,
    currency: 'RUB',
    popularity: 8,
    addedAt: Date.parse('2025-09-02'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'notion-pro-template',
    title: 'Notion Pro — шаблон',
    short: 'Стартовый набор для заметок, планов и проектов.',
    description: 'Файл‑шаблон с базами задач, контент‑планом и CRM для создателя.',
    features: ['Файл-шаблон', 'Готовые базы', 'Гайд по настройке'],
    cover: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 490,
    currency: 'RUB',
    popularity: 6,
    addedAt: Date.parse('2025-08-28'),
    preorder: true,
    payment: { provider: 'plati-market', checkoutUrl: '#REPLACE_PLATI_GOOD_URL' }
  },
  {
    id: 'robux-pack',
    title: 'Roblox — робуксы',
    short: 'Выгодные робуксы с мгновенной доставкой.',
    description: 'Roblox — это игровая платформа с миллионами миров, где каждый может создавать и играть. Робуксы — основная валюта Roblox, необходимая для покупки скинов, анимаций, улучшений и эксклюзивных предметов. На этой странице ты найдешь выгодные предложения на робуксы с мгновенной доставкой. Поддерживаются разные способы оплаты, включая карты, электронные кошельки и мобильные переводы. Пополняй баланс, улучшай стиль аватара и получай доступ к уникальному контенту в любимых играх Roblox.',
    features: ['Мгновенная доставка', 'Разные способы оплаты', 'Официальная валюта Robux'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=946&w=384&h=480&dc=779291494',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 399,
    currency: 'RUB',
    popularity: 7,
    addedAt: Date.parse('2025-09-13'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'gamepass-3m',
    title: 'Xbox Game Pass — 3 месяца',
    short: 'Подписка на 3 месяца. Код активации.',
    description: 'Официальный код Game Pass на 3 месяца. Инструкция и поддержка в комплекте.',
    features: ['3 месяца', 'Инструкция'],
    cover: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 1290,
    currency: 'RUB',
    popularity: 8,
    addedAt: Date.parse('2025-09-14'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'apple-gift-card',
    title: 'Apple Gift Card',
    short: 'Подарочная карта App Store. Пополнение баланса.',
    description: 'Код пополнения баланса Apple ID. Подходит для приложений и подписок.',
    features: ['Код на email', 'Инструкция по активации'],
    cover: 'https://images.unsplash.com/photo-1529612700005-e35377bf1415?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 500,
    currency: 'RUB',
    popularity: 6,
    addedAt: Date.parse('2025-09-10'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'helldivers-2',
    title: 'HELLDIVERS 2',
    short: 'Ключи и Steam‑гифты, быстрый доступ и кооперативный экшен.',
    description: 'Купите ключи и стим-гифты для HELLDIVERS 2 по выгодным ценам! Получите мгновенный доступ к игре через Steam и насладитесь захватывающим кооперативным экшеном. Мы предлагаем оригинальные ключи, безопасные транзакции и быструю доставку на ваш email. Откройте новые уровни и сражайтесь с врагами вместе с друзьями уже сегодня!',
    features: ['Action', 'Кооператив', 'Мгновенная доставка'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1232&w=384&h=480&dc=779291494',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 1790,
    currency: 'RUB',
    popularity: 84,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'borderlands-4',
    title: 'Borderlands 4',
    short: 'Новый шутер с фирменным юмором, тоннами лута и коопом.',
    description: 'Borderlands 4 продолжает культовую серию шутеров с фирменным юмором, динамикой и уникальным визуальным стилем. Игроки получат новых персонажей с особенными навыками, захватывающие битвы с боссами и богатую систему лута. В игре реализованы кооперативные режимы, позволяющие пройти кампанию вместе с друзьями. Огромное количество оружия и неожиданные повороты сюжета делают проект обязательным к покупке. Borderlands 4 доступна на площадке Plati.Market для всех ценителей жанра.',
    features: ['Шутер от первого лица (FPS)', 'Кооперативные режимы', 'Много лута'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1615&w=384&h=480&dc=810989031',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 2190,
    currency: 'RUB',
    popularity: 83,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'music-pack',
    title: 'Музыка PRO — пакет',
    short: 'Доступ к библиотеке без рекламы на 3 месяца.',
    description: 'Подписка на музыкальный сервис без рекламы. Отправим инструкцию после оплаты.',
    features: ['3 месяца', 'Без рекламы'],
    cover: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=1400&auto=format&fit=crop',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 799,
    currency: 'RUB',
    popularity: 5,
    addedAt: Date.parse('2025-09-05'),
    preorder: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'claude-access',
    title: 'Claude',
    short: 'Подписки и аккаунты Claude. Мгновенная доставка и поддержка.',
    description: 'Продажа подписок и аккаунтов Claude по выгодным ценам. Мгновенная доставка, поддержка, гарантия работоспособности. Claude — мощный AI‑помощник для общения, работы и творчества. У нас вы найдете разные варианты подписок на любой срок. Оплата удобным способом. Также доступны предложения на Plati.Market. Выберите подходящий аккаунт уже сегодня.',
    features: ['Подписка Claude', 'Мгновенная доставка', 'Гарантия'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1543&w=384&h=480&dc=795869716',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 1290,
    currency: 'RUB',
    popularity: 82,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'telegram-premium',
    title: 'Telegram Premium',
    short: 'Платная подписка: файлы до 4 ГБ, скорость, без рекламы.',
    description: 'Telegram Premium — это платная подписка, открывающая доступ к расширенному функционалу мессенджера: отправка файлов до 4 ГБ, ускоренная загрузка, голосовые сообщения с преобразованием в текст, уникальные стикеры, анимации, двойной лимит на каналы и чаты, отсутствие рекламы и другие бонусы. Подписка подходит для активных пользователей, которые ценят комфорт и функциональность. На Plati.Market можно быстро приобрести Telegram Premium с удобной активацией.',
    features: ['Файлы до 4 ГБ', 'Ускоренная загрузка', 'Без рекламы'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1099&w=384&h=480&dc=794423436',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 399,
    currency: 'RUB',
    popularity: 81,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  }
  ,
  {
    id: 'black-myth-wukong',
    title: 'Black Myth: Wukong',
    short: 'Ключи и Steam‑гифты. Мгновенная доставка и безопасная оплата.',
    description: 'Приобретайте ключи активации и Steam-гифты для Black Myth: Wukong и погрузитесь в захватывающий мир китайской мифологии. Наш сервис гарантирует мгновенную доставку ключа и безопасные платежи. Откройте доступ к этой эпической игре с уникальной графикой и глубоким сюжетом. Наслаждайтесь выгодными ценами и начните ваше приключение с Black Myth: Wukong уже сегодня!',
    features: ['Ключ активации', 'Steam‑гифт', 'Мгновенная доставка'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1364&w=384&h=480&dc=808858044',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 2190,
    currency: 'RUB',
    popularity: 80,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'hell-is-us',
    title: 'Hell Is Us',
    short: 'Атмосферный экшен с исследованием и мрачной стилистикой.',
    description: 'Hell Is Us — атмосферный экшен с элементами исследования, где игрок сталкивается с таинственными существами и разрушенным миром, переживающим катастрофу. Уникальная система ближнего боя, мрачная визуальная стилистика и глубокий сюжет создают яркий игровой опыт. Вас ждут опасные испытания, продуманная механика оружия и напряжённые сражения. Hell Is Us подойдёт тем, кто ценит современные проекты с авторским стилем и высоким качеством исполнения.',
    features: ['Экшен', 'Исследование', 'Мрачная стилистика'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1519&w=384&h=480&dc=810307455',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 1990,
    currency: 'RUB',
    popularity: 78,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  },
  {
    id: 'cronos-the-new-dawn',
    title: 'Cronos: The New Dawn',
    short: 'RPG с элементами выживания, руинами и системой старения героя.',
    description: 'Cronos: The New Dawn — атмосферная RPG с элементами выживания и сражениями от третьего лица. Игрокам предстоит исследовать древние руины, решать головоломки и сражаться с монстрами, улучшая навыки своего героя. Особенность игры — система старения персонажа, влияющая на стиль боя и способности. Проработанный мир, боевая механика и нелинейный прогресс делают Cronos: The New Dawn интересным выбором для поклонников жанра. Покупайте ключ на Plati.Market и начинайте играть сразу после активации.',
    features: ['RPG', 'Survival', 'От третьего лица'],
    cover: 'https://digiseller.mycdn.ink/imgwebp.ashx?idc=1652&w=384&h=480&dc=810753907',
    images: [],
    category: 'digital',
    type: 'digital',
    price: 1890,
    currency: 'RUB',
    popularity: 77,
    addedAt: Date.parse('2025-09-16'),
    recommended: true,
    payment: { provider: 'payment-link', checkoutUrl: '#REPLACE_PAYMENT_LINK' }
  }
];
